server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  # 브라우저에서 /api/time 호출 → 내부 time-api 서비스로 프록시
  location /api/ {
    proxy_pass http://time-api:8000/;
  }
}
