apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-api
  template:
    metadata:
      labels:
        app: time-api
    spec:
      containers:
        - name: time-api
          image: time-api:1.0
          imagePullPolicy: Never
          env:
            - name: LOGGER_URL
              value: http://logger-api:8000/log
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: time-api
spec:
  selector:
    app: time-api
  ports:
    - port: 8000
      targetPort: 8000
